changelog:
  categories:
    - title: 🚀 Features
      labels: [ enhancement, feature ]
    - title: 🐛 Bug Fixes
      labels: [ bug, fix ]
    - title: 📦 Dependencies
      labels: [ dependencies ]
    - title: Other Changes
      labels: [ "*" ]
