package com.symphony.bdk.core.auth;

import com.symphony.bdk.core.auth.exception.AuthUnauthorizedException;

import org.apiguardian.api.API;

import javax.annotation.Nonnull;

/**
 * Extension App Authenticator Service.
 */
@API(status = API.Status.STABLE)
public interface ExtensionAppAuthenticator {

  /**
   * Authenticates an extension app.
   *
   * @param appToken The token generated by application backend.
   * @return the extension app authentication session.
   * @throws AuthUnauthorizedException when the bot is unauthorized.
   */
  @Nonnull
  AppAuthSession authenticateExtensionApp(String appToken) throws AuthUnauthorizedException;

}
