package com.symphony.bdk.app.spring.auth.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * App Token generated by the application.
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
public class AppToken {

  private String appToken;
}
