package com.symphony.bdk.app.spring.auth.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;

/**
 * A pair of tokens used during the Circle of Trust authentication.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class TokenPair {

  /**
   * {@link AppToken} generated by the Extension App Backend.
   */
  @NotBlank(message = "App Token is mandatory")
  private String appToken;

  /**
   * Symphony Token generated by the Symphony Backend.
   */
  @NotBlank(message = "Symphony Token is mandatory")
  private String symphonyToken;
}
