name: Build

on:
  push:
    branches: [ 'main', '*-rc' ]
  pull_request:
    branches: [ 'main', '*-rc' ]

jobs:
  build:
    name: "Build"

    runs-on: ubuntu-latest

    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: build jacocoTestReport jacocoTestCoverageVerification

    - name: Publish SNAPSHOT artifacts
      if: github.event_name == 'pull_request' && env.MAVEN_USERNAME != ''
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: publishToSonatype -PmavenRepoUsername=${{ secrets.MAVEN_USERNAME }} -PmavenRepoPassword=${{ secrets.MAVEN_PASSWORD }}

